# Generated by Django 4.1.7 on 2023-04-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_category_employee_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
